name: CF-Clean-IP-Scan
on:
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Scan Script
        run: |
          wget https://raw.githubusercontent.com/vfarid/cf-clean-ip/main/run.sh
          chmod +x run.sh
          ./run.sh
